# Access   : via SSH tunnel through the router bastion (port 5601 not exposed)

server.port: 5601
server.host: "192.168.30.10"
server.name: "kibana-siem"
elasticsearch.hosts: ["http://192.168.30.10:9200"]
